/** Named constants — tuned per REVAMP_PLAN Phase 1 (45–65 day Mara arc). */
export const TUNING = {
  mealGainFactor: 0.12,
  appetiteGrowthPerMeal: 0.012,
  appetiteDecayPerDay: 0.01,
  appetiteCapPreFlip: 1.6,
  appetiteCapFlipped: 3.0,
  appetiteFloorPerRung: 0.04,
  fullnessPerMeal: 0.32,
  fullnessDecayPerSlot: 0.12,
  capacityGrowthThreshold: 1.1,
  capacityGrowthRate: 0.02,
  windowOpenFactor: 0.92,
  windowCertainFactor: 1.18,
  windowRampExponent: 1.5,
  fullnessModThreshold: 0.8,
  fullnessMod: 1.5,
  spurtMod: 2.0,
  nearMissBand: 1.6,
  nearMissWearAdd: 0.05,
  nearMissWearCap: 0.5,
  imminentThreshold: 0.5,
  approachingLbs: 15,
  driftT1: 8,
  driftT2: 20,
  driftT3: 35,
  softeningPerCrown: 3,
  softeningPerReplacement: 1,
  softeningPerDriftT2: 1,
  softeningPerDriftT3: 2,
  argPressurePerPublicFire: 8,
  argPressurePerRung: 5,
  slotsPerDay: 3,
  arcTargetDaysMin: 45,
  arcTargetDaysMax: 70,
  crownSpurtLbs: 10,
  saveVersion: 1,
};
