/** Named constants — expect flag-batch tuning. */
export const TUNING = {
  mealGainFactor: 0.4,
  appetiteGrowthPerMeal: 0.02,
  appetiteDecayPerDay: 0.01,
  fullnessPerMeal: 0.25,
  fullnessDecayPerSlot: 0.15,
  capacityGrowthThreshold: 1.1,
  capacityGrowthRate: 0.02,
  windowOpenFactor: 0.92,
  windowCertainFactor: 1.18,
  windowRampExponent: 1.5,
  fullnessModThreshold: 0.8,
  fullnessMod: 1.5,
  spurtMod: 2.0,
  nearMissWearAdd: 0.05,
  imminentThreshold: 0.5,
  approachingLbs: 15,
  driftT1: 8,
  driftT2: 20,
  driftT3: 35,
  softeningPerCrown: 3,
  softeningPerReplacement: 1,
  softeningPerDriftT2: 1,
  softeningPerDriftT3: 2,
  argPressurePerPublicFire: 8,
  argPressurePerRung: 5,
  slotsPerDay: 3,
  arcTargetDaysMin: 40,
  arcTargetDaysMax: 70,
  saveVersion: 1,
};
